[workspace]
members = [
    "sss-lib/render",
    "sss-lib/parser",
    "sss-lib/sss-core",
    "sss-lib/sss-std",
    "sss-cli"
]
resolver = "2"

[workspace.package]
version = "1.0.0"
edition = "2021"
authors = ["TOwInOK <60252419+TOwInOK@users.noreply.github.com>"]
repository = "https://github.com/TOwInOK/SSS-rs"
license = "Apache-2.0"

[workspace.metadata.docs]
rs-doc-path = "docs"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
tokio = { version = "1", features = ["full"] }
thiserror = "2.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
encre-css = "0.14.1"
anyhow = "1.0.95"
clap = { version = "4.5.23", features = [ "derive"] }
toml = "0.8.19"

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false
lto = true
codegen-units = 1
panic = 'abort'

[profile.test]
opt-level = 0
debug = true

[profile.bench]
opt-level = 3
debug = false
