theme = "UMBRELLA"
layout = "UMBRELLA"

[user]
specifications = [
    "Your",
    "cool",
    "way",
]
about = "Something about yourself"

[user.user]
name = "Your name"

[user.user.current_nickname]
word = "Some Nickname"
pronounce = "sÔme nIckname"

[[user.user.prevision_nicknames]]
word = "Your some old nickname"
pronounce = "sÔme OLDER nIckname"

[[user.repos]]
name = "Cool Project"

[user.repos.link]
provider = "Github"
link = "https://github.com/your_nickname"

[[user.repos]]
name = "Cool Project"

[user.repos.link]
provider = "Github"
link = "https://github.com/your_nickname"

[[user.socials]]
provider = "Github"
link = "https://github.com/your_nickname"

[[user.socials]]
provider = "Telegram"
link = "https://t.me/your_nickname"

[[user.skills]]
skill = "Rust"
main = true

[[user.skills.projects]]
name = "Cool Project"

[user.skills.projects.link]
provider = "Github"
link = "https://github.com/your_nickname"

[user.skills.since]
start = 2020
end = 0

[user.skills.repo_link]
provider = "Github"
link = "https://github.com/your_nickname"

[[user.skills]]
skill = "JS/TS"
main = false

[[user.skills.projects]]
name = "Cool Project"

[user.skills.projects.link]
provider = "Github"
link = "https://github.com/your_nickname"

[user.skills.since]
start = 2020
end = 2022

[user.skills.repo_link]
provider = "Github"
link = "https://github.com/your_nickname"
