use super::{Shade, Theme};

pub static UMBRELLA_LIGHT: Shade = Shade::Light(Theme {
    primary: "",
    secondary: "",
    thirdly: "",
    border: "",
    button_pudding: 0,
    border_pudding: 0,
    frame_pudding: 0,
    button_gap: 0,
    border_gap: 0,
    frame_gap: 0,
    label_style: "",
    sub_label_style: "",
    text_style: "",
    text_minor_style: "",
    link_style: "",
    frame_style: "",
    icon_style: "",
    vertical_frame_style: "",
    horizontal_frame_style: "",
    revers_vertical_frame_style: "",
    revers_horizontal_frame_style: "",
});

pub static UMBRELLA_DARK: Shade = Shade::Dark(Theme {
    primary: "",
    secondary: "",
    thirdly: "",
    border: "",
    button_pudding: 0,
    border_pudding: 0,
    frame_pudding: 0,
    button_gap: 0,
    border_gap: 0,
    frame_gap: 0,
    label_style: "",
    sub_label_style: "",
    text_style: "",
    text_minor_style: "",
    link_style: "",
    frame_style: "",
    icon_style: "",
    vertical_frame_style: "",
    horizontal_frame_style: "",
    revers_vertical_frame_style: "",
    revers_horizontal_frame_style: "",
});
