[package]
name = "tabler-icon-definer"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license = "MIT"
description = "Macros for fast incremental loading tabler icons"

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
reqwest = { version = "0.11", features = ["blocking"] }

[lib]
proc-macro = true
