# имя
name = "Your name"
# Прозвище
nickname = { word = "TOwInOK", prononce = "tOowInOok" } # prononce не обязателен
# Иный прозвища
other_nicknames = [
    { word = "nqcq", prononce = "" },
    { word = "cqnq" },                # prononce не обязателен
]
# На что делаете уклон?
specifications = ["Backend", "Fullstack"]
# о вас. Скрывается после { max_length } символов, можно будет развернуть
about = { text = "Some huge text :/", max_length = 100 } # max_length по умолчанию 100
# Репозитории
repos = [
    { provider = "GitHub", link = "https://github.com/your_project1", logo = "direct_link.png || svg", main = true }, # main по умолчанию false
    { provider = "GitHub", link = "https://github.com/your_project1" },                                               # logo по умолчанию стандартного в теме
]
# Социальные сети
social_media = [
    { provider = "Facebook", link = "https://facebook.com/your_profile", logo = "", main = true }, # main по умолчанию false
    { provider = "Steam", link = "https://steamcommunity.com/your_profile" },
    { provider = "Instagram", link = "https://instagram.com/your_profile" },
    { provider = "X", link = "https://twitter.com/your_profile" },
    { provider = "Spotify", link = "https://spotify.com/your_profile" },
]

[[skills]]
skill = "rust"
# Топ проектов
top_projects = [
    { provider = "GitHub", link = "https://github.com/your_project1", logo = "custom_logo.svg", main = true },
    { provider = "GitHub", link = "https://github.com/your_project2" },
    { provider = "GitLab", link = "https://gitlab.com/your_project3" },
]

since = { start = 2020, end = 0 }             # если end = 0, то по сегодня. Не обязательное поле
main = true
maintainer_site = "https://crates.io/TOwInOK"


[[skills]]
skill = "javascript"
top_projects = [
    { provider = "GitHub", link = "https://github.com/your_js_project" },
    { provider = "GitHub", link = "https://github.com/another_js_project" },
]
since = { start = 2018, end = 2022 }
main = false

[[skills]]
skill = "typescript"
top_projects = [{ provider = "GitHub", link = "https://github.com/ts_project" }]
since = { start = 2019, end = 0 }
main = true
maintainer_site = "https://www.npmjs.com/~your_profile"
