[package]
name = "render"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
sss_core = { path = "../sss-core" }
serde.workspace = true
serde_json.workspace = true
